const { Document, Packer, Paragraph, TextRun } = require("docx");

exports.main = async (context = {}) => {
  const { propertiesToSend, parameters } = context;
  const props = propertiesToSend || {};
  const userId = parameters?.userId || "unknown";

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            children: [
              new TextRun({
                text: "Thalamus Institutional Quote",
                bold: true,
                size: 28,
              }),
            ],
          }),
          new Paragraph({}),
          new Paragraph({
            text: `Institution Name: ${props.institution_name_sync || "N/A"}`,
          }),
          new Paragraph({
            text: `GME ID: ${props.acgme_institution_id_sync || "N/A"}`,
          }),
          new Paragraph({ text: `Application Season: 2025-2026` }),
          new Paragraph({ text: `Generated by user: ${userId}` }),
          new Paragraph({ text: `Date: ${new Date().toLocaleDateString()}` }),
        ],
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  const base64 = buffer.toString("base64");

  return {
    statusCode: 200,
    body: {
      success: true,
      message: "DOCX document generated",
      filename: `institution_quote_${Date.now()}.docx`,
      document: base64,
      mimeType:
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    },
  };
};
